"""Full, unchanged HTML loaded with set_content. The environment blocks file navigation.
Explicit storage adapters test consent, reload, denial and import; no server/AI mocks.
"""
from pathlib import Path
import json, shutil, traceback
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
HTML=((ROOT/'catgpt.html') if (ROOT/'catgpt.html').exists() else (ROOT/'build/catgpt.html')).read_text()
OUT=ROOT/'results'; fixtures={p.stem:json.loads(p.read_text()) for p in (OUT/'fixtures').glob('*.json')}
results=[];errors=[];requests=[]
def check(v,msg='Assertion failed'):
    assert v,msg

def record(name,fn):
    try:fn();results.append({'name':name,'passed':True});print('PASS',name,flush=True)
    except Exception as e:results.append({'name':name,'passed':False,'error':str(e)[:1800]});print('FAIL',name,str(e)[:240],flush=True)
def s(p):return p.evaluate('CatGameUI.getState()')
def click(p,sel):p.locator(sel).click();p.wait_for_timeout(180)
def choose(p,id):click(p,f'#choices [data-choice="{id}"]')
with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=shutil.which('chromium'),headless=True,args=['--no-sandbox'])
    def new_page(w=1440,h=940,fixture=None,storage='memory',initial=None):
        p=browser.new_page(viewport={'width':w,'height':h},is_mobile=w<=620,has_touch=w<=620,device_scale_factor=1)
        p.set_default_timeout(5000);p.on('pageerror',lambda e:errors.append(str(e)));p.on('request',lambda r:requests.append(r.url) if r.url.startswith(('http:','https:')) else None)
        store=initial or {}
        if fixture:store['catgpt.game.v3']=json.dumps(fixtures[fixture])
        if storage=='memory':
            p.evaluate('''initial=>{window.__store=new Map(Object.entries(initial));window.__failWrites=false;window.__silentWrites=false;Object.defineProperty(window,'localStorage',{value:{getItem:k=>__store.get(k)||null,setItem:(k,v)=>{if(__failWrites)throw Error('quota');if(!__silentWrites)__store.set(k,String(v));},removeItem:k=>__store.delete(k)},configurable:true});}''',store)
        elif storage=='denied':p.evaluate("Object.defineProperty(window,'localStorage',{get(){throw new DOMException('denied','SecurityError')}})")
        p.set_content(HTML,wait_until='load');p.wait_for_function('!!window.CatGameUI')
        return p
    p=new_page()
    record('Startup: exact HTML initializes, default consent off, 33 photos',lambda:(check(p.locator('#app').is_visible()),check(not p.locator('#landingSave').is_checked()),check(p.evaluate('JSON.parse(document.getElementById("catAssets").textContent).photos.length')==33)))
    record('Desktop starts without horizontal overflow',lambda:check(p.evaluate('document.documentElement.scrollWidth<=innerWidth')))
    p.screenshot(path=str(OUT/'start-desktop.png'))
    click(p,'#startButton')
    record('Starts as a conversation with three specific replies',lambda:(check(s(p)['node']=='c1_welcome'),check(p.locator('#choices .choice-card').count()==3)))
    p.screenshot(path=str(OUT/'chat-start.png'))
    choose(p,'rights')
    record('Selected sentence and matching sarcastic response remain in main chat',lambda:(check('Bevor das hier' in p.locator('.user-bubble').last.inner_text()),check('Selbstachtung' in p.locator('.direct-reply').last.inner_text()),check(s(p)['node']=='c1_pay')))
    record('Scroll keeps direct reaction in the visible conversation area',lambda:check(p.locator('.direct-reply').last.evaluate('(e)=>{const r=e.getBoundingClientRect(),s=document.getElementById("storyScroll").getBoundingClientRect();return r.top>=s.top-2&&r.bottom<=s.bottom+2}')))
    record('Previous prompt is retained rather than replaced by another slide',lambda:check(p.locator('[data-scene="c1_welcome"]').count()==1 and p.locator('[data-scene="c1_pay"]').count()==1))
    p.screenshot(path=str(OUT/'chat-response.png'))
    record('Old choice revision is rejected without advancing or scoring twice',lambda:check(not p.evaluate("CatGameUI.dispatch({type:'choose',node:'c1_welcome',id:'rights',r:1})") and s(p)['stats']['substance']==1))
    p.keyboard.press('1');p.wait_for_timeout(200)
    record('Keyboard choice sends actual answer and its boundary intention',lambda:check(s(p)['node']=='c1_board' and s(p)['flags']['boundary']))
    p.locator('#chapterNav [data-chapter="1"]').click();p.locator('#confirmNo').click()
    record('Cancel chapter restart preserves conversation state',lambda:check(s(p)['node']=='c1_board'))
    p.locator('#chapterNav [data-chapter="1"]').click();p.locator('#confirmYes').click()
    record('Confirmed chapter restart resets messages and later choices',lambda:check(s(p)['node']=='c1_welcome' and p.locator('.user-bubble').count()==0))
    p.wait_for_timeout(200);p.locator('#choices [data-choice="job"]').dblclick(delay=25);p.wait_for_timeout(220)
    record('Double click cannot consume the following choice',lambda:check(s(p)['node']=='c1_job' and len([e for e in s(p)['events'] if e['type']=='choose'])==1))
    # Chapter boundary, true UI click, no time-based advance.
    b=new_page(fixture='boundary');click(b,'#startButton');choose(b,'go')
    record('Last answer is shown while still in chapter one',lambda:check(s(b)['chapter']==1 and s(b)['node']=='c1_scope' and bool(s(b)['pending'])))
    record('Boundary text announces the destination and confirmation is available',lambda:check('öffnen wir jetzt den Schrank' in b.locator('.direct-reply').last.inner_text() and b.locator('#advanceButton').is_visible()))
    b.wait_for_timeout(500)
    record('Chapter does not auto-advance after waiting',lambda:check(s(b)['chapter']==1))
    click(b,'#advanceButton')
    record('Only explicit confirmation enters the next chapter, with prior reply intact',lambda:check(s(b)['chapter']==2 and b.locator('[data-scene="c1_scope"]').count()==1 and 'öffnen wir jetzt den Schrank' in b.locator('.direct-reply').last.inner_text()))
    b.evaluate("const n=document.querySelector('[data-scene=\"c2_office\"]');const s=document.getElementById('storyScroll');s.scrollTop+=n.getBoundingClientRect().top-s.getBoundingClientRect().top-16;")
    b.screenshot(path=str(OUT/'office-chat.png'))
    # Gallery, all embedded originals, accessible lightbox.
    p.locator('.top-tools [data-action="gallery"]').click()
    record('All 33 photos available before completion',lambda:check(p.locator('#galleryGrid .gallery-item').count()==33))
    p.locator('#gallerySearch').fill('14')
    record('Excluded photo 14 is not reintroduced',lambda:check(p.locator('#galleryGrid .gallery-item').count()==0))
    p.locator('#gallerySearch').fill('1000601348')
    record('Filename search returns exact photo',lambda:check(p.locator('#galleryGrid .gallery-item').count()==1 and p.locator('#galleryGrid .gallery-item').get_attribute('data-photo')=='paws'))
    p.locator('#gallerySearch').fill('');p.locator('#galleryFilters [data-filter="new"]').click()
    record('Eleven latest photos remain filtered and reachable',lambda:check(p.locator('#galleryGrid .gallery-item').count()==11))
    p.locator('#galleryFilters [data-filter="all"]').click();p.locator('#galleryGrid .gallery-item').first.click()
    def all_images():
        seen=set()
        for i in range(33):
            p.wait_for_function('document.getElementById("lightboxImage").complete&&document.getElementById("lightboxImage").naturalWidth>0')
            seen.add(p.locator('#lightboxFile').inner_text());p.locator('#nextPhoto').click()
        check(len(seen)==33)
    record('All 33 full-motif images decode in the gallery',all_images)
    before=p.locator('#lightboxCount').inner_text();p.keyboard.press('ArrowRight')
    record('Lightbox keyboard navigation works',lambda:check(p.locator('#lightboxCount').inner_text()!=before))
    p.keyboard.press('Escape')
    record('Escape closes modal and returns to chat',lambda:check(not p.locator('#galleryDialog').is_visible()))
    before=s(p);p.locator('[data-action="history"]').first.click()
    record('History includes own reply and original Ted reaction',lambda:check('Niedrige Einstiegshürde' in p.locator('#historyBody').inner_text()))
    p.locator('#historyBody .log-heading').first.click()
    record('Reading old messages does not change any gameplay state',lambda:check(s(p)==before))
    p.close();b.close()
    # Actual room movement, pickup, return and optional second round.
    ballp=new_page(fixture='ball');click(ballp,'#startButton');ballp.locator('#roomGrid').focus();ballp.keyboard.press('ArrowUp')
    record('Room arrow keys move human, not the story',lambda:check(s(ballp)['games']['ball']['y']==3 and s(ballp)['node']=='c2_ball'))
    ballp.screenshot(path=str(OUT/'ball-desktop.png'))
    for _ in range(3):ballp.locator('#move-up').click()
    for _ in range(5):ballp.locator('#move-right').click()
    click(ballp,'#ballPick')
    record('Ball pickup requires reaching its room position',lambda:check(s(ballp)['games']['ball']['held']))
    for _ in range(5):ballp.locator('#move-left').click()
    for _ in range(4):ballp.locator('#move-down').click()
    click(ballp,'#ballDeliver')
    record('Ted reacts before player secures or throws ball',lambda:check(s(ballp)['games']['ball']['phase']=='settle' and ballp.locator('#ballThrow').is_visible()))
    click(ballp,'#ballThrow')
    record('Optional extra round relocates ball but no chapter',lambda:check(s(ballp)['games']['ball']['ball']==[6,4] and s(ballp)['chapter']==2))
    for _ in range(6):ballp.locator('#move-right').click()
    click(ballp,'#ballPick')
    for _ in range(6):ballp.locator('#move-left').click()
    click(ballp,'#ballDeliver')
    record('Extra round cannot repeat indefinitely',lambda:check(ballp.locator('#ballThrow').count()==0))
    click(ballp,'#ballBox')
    record('Ball completion shows precise result and waits for discussion',lambda:check(s(ballp)['games']['ball']['boxed'] and s(ballp)['pending']['kind']=='game' and 'Karton' in ballp.locator('.direct-reply').last.inner_text()))
    click(ballp,'#advanceButton')
    record('Ball result and employee-representation callback are present',lambda:check(s(ballp)['node']=='c2_result' and 'Mitarbeitervertretung' in ballp.locator('[data-scene="c2_result"]').inner_text()))
    ballp.close()
    # Food order from UI, mistakes reversible and named, no pretend LLM.
    f=new_page(390,844,fixture='food');click(f,'#startButton');click(f,'#food-menu-luxury');click(f,'#food-bowl-gold');click(f,'#foodServe')
    record('Wrong food order names what is missing without resetting menu',lambda:check('blaue Schale' in f.locator('#gameFeedback').inner_text() and s(f)['games']['food']['menu']=='luxury'))
    click(f,'#food-menu-house');click(f,'#food-bowl-blue');click(f,'#portionPlus');click(f,'#portionPlus');click(f,'#portionPlus');click(f,'#portionMinus');click(f,'#foodWater')
    record('Portions adjustable both ways, water accepted once',lambda:check(s(f)['games']['food']['scoops']==2 and f.locator('#foodWater').is_disabled()))
    f.locator('#miniTitle').scroll_into_view_if_needed();f.screenshot(path=str(OUT/'food-mobile.png'))
    click(f,'#foodServe')
    record('Correct order opens Ted-specific finishing choices',lambda:check(s(f)['games']['food']['served'] and f.locator('#foodLabel').is_visible() and f.locator('#foodWalk').is_visible()))
    click(f,'#foodLabel');click(f,'#advanceButton')
    record('Chefedition choice changes subsequent Ted dialogue',lambda:check('Chefedition' in f.locator('[data-scene="c3_result"]').inner_text()))
    f.close()
    # Litter: real tile actions, tools, capacity, completion and boundary.
    l=new_page(390,844,fixture='litter');click(l,'#startButton');click(l,'#litter-cell-20')
    record('Wrong tool for paw marks explains broom requirement',lambda:check('Besen' in l.locator('#gameFeedback').inner_text() and s(l)['games']['litter']['cleaned']==[]))
    for cell in [2,6,9]:click(l,f'#litter-cell-{cell}')
    click(l,'#litter-cell-12')
    record('Full litter bin blocks another clump without losing progress',lambda:check(s(l)['games']['litter']['bin']==3 and len(s(l)['games']['litter']['cleaned'])==3))
    click(l,'#litterEmpty');click(l,'#litter-cell-12');click(l,'#litter-cell-17');click(l,'#litterEmpty');click(l,'#tool-broom')
    for cell in [20,21,22,23]:click(l,f'#litter-cell-{cell}')
    l.locator('#miniTitle').scroll_into_view_if_needed();l.screenshot(path=str(OUT/'litter-mobile.png'))
    record('Litter task includes all five clumps and four tracks',lambda:check(len(s(l)['games']['litter']['cleaned'])==9 and s(l)['games']['litter']['bin']==0))
    click(l,'#litterFill');click(l,'#litterFill');click(l,'#litterInspect')
    record('Inspection is interactive and not an automatic scene jump',lambda:check(s(l)['node']=='c4_litter' and l.locator('#litterDocument').is_visible()))
    click(l,'#litterDocument');click(l,'#advanceButton')
    record('Documented cleaning is acknowledged in Ted follow-up',lambda:check('Abnahme festgehalten' in l.locator('[data-scene="c4_result"]').inner_text()))
    l.close()
    # Every ending actually rendered from a validated event-only save.
    for ending in ['founder','human','rest','exit']:
        e=new_page(fixture=ending);click(e,'#startButton')
        record('Ending '+ending+' renders final reply, receipt and completed tasks',lambda e=e,ending=ending:check(s(e)['ending']==ending and e.locator('#endingCard').is_visible() and e.locator('.result-stamps span').count()==3))
        if ending=='rest':e.locator('#endingCard').scroll_into_view_if_needed();e.screenshot(path=str(OUT/'ending-desktop.png'))
        e.close()
    # Consent, reload, denial, corrupted data and validated UI import.
    sp=new_page(initial={'catgpt.game.v2':'OLD_DATA'});click(sp,'#startButton');choose(sp,'boss');sp.locator('.top-tools [data-action="settings"]').click();sp.locator('#settingSave').check()
    record('Consent stores v3 only and leaves prior version key untouched',lambda:check(sp.evaluate("__store.get('catgpt.game.v2')==='OLD_DATA'&&__store.has('catgpt.game.v3')")))
    stored=sp.evaluate('Object.fromEntries(__store)');rp=new_page(initial=stored);click(rp,'#startButton')
    record('Reload replays saved user and Ted messages at the same branch',lambda:check(s(rp)['node']=='c1_origin' and 'Erwartungshaltung' in rp.locator('.direct-reply').last.inner_text()))
    sp.locator('#settingSave').uncheck()
    record('Disabling persistence removes only current version save',lambda:check(sp.evaluate("!__store.has('catgpt.game.v3')&&__store.get('catgpt.game.v2')==='OLD_DATA'")))
    sp.evaluate('__failWrites=true');sp.locator('#settingSave').click()
    record('Failed save is not falsely reported as saved',lambda:check(not sp.locator('#settingSave').is_checked() and 'kein verlässliches Speichern' in sp.locator('#settingsState').inner_text()))
    denied=new_page(storage='denied');click(denied,'#startButton');choose(denied,'job')
    record('Denied local storage does not stop the game',lambda:check(s(denied)['node']=='c1_job' and 'Speicher' in denied.locator('#saveState').inner_text()))
    corrupt=new_page(initial={'catgpt.game.v3':'invalid-json'});click(corrupt,'#startButton')
    record('Corrupt save is not overwritten by starting without persistence',lambda:check(corrupt.evaluate("__store.get('catgpt.game.v3')==='invalid-json'")))
    ip=new_page();click(ip,'#startButton');ip.locator('.top-tools [data-action="settings"]').click();ip.locator('#saveFile').set_input_files(str(OUT/'fixtures/food.json'));ip.locator('#confirmYes').click();ip.wait_for_timeout(250)
    record('JSON file import reconstructs current minigame via UI',lambda:check(s(ip)['node']=='c3_food' and ip.locator('#miniGame').is_visible()))
    ip.locator('.top-tools [data-action="settings"]').click();ip.locator('#saveFile').set_input_files({'name':'old.json','mimeType':'application/json','buffer':json.dumps({'format':'CATGPT_TED_GAME','schema':2,'endings':[],'events':[]}).encode()})
    record('Old incompatible import is refused, current branch preserved',lambda:check(s(ip)['node']=='c3_food' and 'nicht zum Chat-Spiel' in ip.locator('#toast').inner_text()))
    with ip.expect_download() as info:ip.locator('#exportSave').click()
    dl=info.value;dl.save_as(str(OUT/'browser-export.json'))
    record('Export downloads a valid current-format event-only save',lambda:check(json.loads((OUT/'browser-export.json').read_text())['schema']==3))
    for old in [sp,rp,denied,corrupt,ip]:old.close()
    # Several mobile/desktop sizes, photo replies and games.
    for w,h in [(320,740),(360,780),(390,844),(768,1024),(1024,768),(1440,940),(844,390)]:
        vp=new_page(w,h,fixture='litter');click(vp,'#startButton')
        record(f'Viewport {w}x{h}: no horizontal overflow and game controls scroll-reachable',lambda vp=vp:check(vp.evaluate('document.documentElement.scrollWidth<=innerWidth') and vp.locator('#tool-scoop').is_visible()))
        vp.locator('.top-tools [data-action="settings"]').click();vp.locator('#settingLarge').click();vp.keyboard.press('Escape')
        record(f'Large text {w}x{h}: layout remains within viewport',lambda vp=vp:check(vp.evaluate('document.documentElement.scrollWidth<=innerWidth')))
        vp.close()
    mobile=new_page(390,844);click(mobile,'#startButton');choose(mobile,'rights');mobile.screenshot(path=str(OUT/'chat-mobile.png'))
    record('Mobile direct answer is visible before next-topic photo or chapter',lambda:check(mobile.locator('.direct-reply').last.evaluate('(e)=>{const a=e.getBoundingClientRect(),b=document.getElementById("storyScroll").getBoundingClientRect();return a.top>=b.top&&a.bottom<=b.bottom}')))
    record('No uncaught browser errors in all tested flows',lambda:check(not errors,str(errors)))
    record('No HTTP requests made by the offline game',lambda:check(not requests,str(requests)))
    browser.close()
(OUT/'browser-results.json').write_text(json.dumps({'passed':sum(r['passed'] for r in results),'total':len(results),'tests':results,'errors':errors,'requests':requests,'method':'Exact unchanged HTML with set_content; file navigation blocked by environment; explicit storage adapters.'},ensure_ascii=False,indent=2))
print('TOTAL',sum(r['passed'] for r in results),'/',len(results),flush=True)
if any(not r['passed'] for r in results):raise SystemExit(1)
