import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import {fileURLToPath} from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const html=fs.readFileSync((fs.existsSync(path.join(ROOT,'catgpt.html'))?path.join(ROOT,'catgpt.html'):path.join(ROOT,'build/catgpt.html')),'utf8');
vm.runInThisContext(html.match(/<script id="gameCore">([\s\S]*?)<\/script>/)[1]);
const G=globalThis.CatGame;
const assets=JSON.parse(html.match(/<script type="application\/json" id="catAssets">([\s\S]*?)<\/script>/)[1]);
const act=(s,e)=>G.reduce(s,{...e,r:s.events.length});
const choose=(s,id)=>act(s,{type:'choose',node:s.node,id});
const start=()=>act(G.fresh(),{type:'start'});
function routeTo(g,goal){let q=[[g.x,g.y,[]]],seen=new Set();while(q.length){const [x,y,p]=q.shift();if(x===goal[0]&&y===goal[1])return p;const k=x+','+y;if(seen.has(k))continue;seen.add(k);for(const [d,[dx,dy]] of Object.entries(G.DIRECTIONS)){const nx=x+dx,ny=y+dy;if(nx>=0&&ny>=0&&nx<7&&ny<5&&!G.ROOM.blocks.some(b=>b.x===nx&&b.y===ny))q.push([nx,ny,[...p,d]]);}}throw Error('no path');}
function ball(s,{extra=false,method='box'}={}){
 const fetch=()=>{for(const dir of routeTo(s.games.ball,s.games.ball.ball))s=act(s,{type:'ball_move',dir});s=act(s,{type:'ball_pick'});for(const dir of routeTo(s.games.ball,[0,4]))s=act(s,{type:'ball_move',dir});s=act(s,{type:'ball_deliver'});};
 fetch();if(extra){s=act(s,{type:'ball_finish',method:'throw'});fetch();}return act(s,{type:'ball_finish',method});
}
function food(s,method='walk'){s=act(s,{type:'food_pick',group:'menu',id:'house'});s=act(s,{type:'food_pick',group:'bowl',id:'blue'});s=act(s,{type:'food_scoop',delta:1});s=act(s,{type:'food_scoop',delta:1});s=act(s,{type:'food_water'});s=act(s,{type:'food_serve'});return act(s,{type:'food_finish',method});}
function litter(s,method='document'){for(const cell of G.LITTER.clumps){if(s.games.litter.bin===3)s=act(s,{type:'litter_empty'});s=act(s,{type:'litter_clean',cell});}s=act(s,{type:'litter_empty'});s=act(s,{type:'litter_tool',tool:'broom'});for(const cell of G.LITTER.tracks)s=act(s,{type:'litter_clean',cell});s=act(s,{type:'litter_fill'});s=act(s,{type:'litter_fill'});s=act(s,{type:'litter_inspect'});return act(s,{type:'litter_finish',method});}
const base={c1_welcome:'rights',c1_pay:'credit',c1_board:'chair',c1_chair:'keep',c1_upright:'line',c1_scope:'go',c2_office:'room',c2_team:'rights',c2_remote:'remote',c2_result:'mine',c2_outpost:'trip',c2_lamp:'credit',c2_desk:'space',c2_space:'save',c2_protocol:'save',c2_security:'go',c3_hunger:'hungry',c3_growth:'eat',c3_order:'repeat',c3_result:'pause',c3_agreement:'credit',c3_pivot:'third',c4_mission:'gear',c4_tools:'scope',c4_result:'mine',c4_debrief:'thanks',c4_thanks:'joke',c4_edge:'suspicious',c5_reveal:'knew',c5_terms:'credit',c5_contact:'pet',c5_balance:'founder'};
function walk(route=base,opts={}){
 let s=start(),guard=0;while(!s.complete&&s.node!==opts.until){if(++guard>200)throw Error('Loop');if(s.pending){s=act(s,{type:'advance'});continue;}const game=G.STORY[s.node].game;if(game){s=opts.skip?act(s,{type:'skip',game}):game==='ball'?ball(s,opts):game==='food'?food(s,opts.foodMethod):litter(s,opts.litterMethod);continue;}const cs=G.choices(s),id=route[s.node]||cs[0].id;assert.ok(cs.some(c=>c.id===id),`${s.node}:${id}`);s=choose(s,id);}return s;
}
const snapshots={ball:walk(base,{until:'c2_ball'}),food:walk(base,{until:'c3_food'}),litter:walk(base,{until:'c4_litter'}),boundary:walk(base,{until:'c1_scope'})};
fs.mkdirSync(path.join(ROOT,'results/fixtures'),{recursive:true});for(const [k,v]of Object.entries(snapshots))fs.writeFileSync(path.join(ROOT,'results/fixtures',k+'.json'),JSON.stringify(G.pack(v)));
const endings=['founder','human','rest','exit'];
test('44 authored scenes, five chapters, four endings, three everyday games',()=>{assert.equal(Object.keys(G.STORY).length,44);assert.equal(G.CHAPTERS.length,5);assert.equal(Object.keys(G.ENDINGS).length,4);assert.deepEqual(Object.values(G.STORY).filter(n=>n.game).map(n=>n.game),['ball','food','litter']);});
test('All 33 approved assets retained; no photo 14 or excluded filename',()=>{assert.equal(assets.photos.length,33);assert.equal(new Set(assets.photos.map(p=>p.id)).size,33);assert.ok(assets.photos.every(p=>p.number!==14&&p.filename!=='1000601355.jpg'&&p.src.startsWith('data:image/')));assert.deepEqual(Object.keys(G.PHOTO_STORY).sort(),assets.photos.map(p=>p.id).sort());});
test('Offline: no requests, runtime AI, libraries or form endpoints',()=>{const js=html.match(/<script id="gameUI">([\s\S]*?)<\/script>/)[1];assert.ok(!/\bfetch\s*\(|XMLHttpRequest|WebSocket|<script[^>]+src=/.test(js));assert.ok(html.includes("connect-src 'none'"));});
test('Every response has a unique local ID, own reaction and valid destination',()=>{for(const n of Object.values(G.STORY)){assert.ok(n.end||n.game||n.choices.length);assert.equal(n.choices.length,new Set(n.choices.map(c=>c.id)).size);for(const c of n.choices){assert.ok(G.STORY[c.next]);assert.ok(typeof c.reply==='function'||c.reply.length>20);assert.ok(n.chapter<=G.STORY[c.next].chapter);}}});
test('Graph is acyclic and every scene is structurally reachable',()=>{const seen=new Set(),active=new Set();function go(id){assert.ok(!active.has(id),id);if(seen.has(id))return;active.add(id);const n=G.STORY[id];for(const c of n.choices)go(c.next);if(n.game)go({ball:'c2_result',food:'c3_result',litter:'c4_result'}[n.game]);active.delete(id);seen.add(id);}go('c1_welcome');assert.equal(seen.size,44);});
for(const ending of endings)test('Full route '+ending+' retains all photos and full transcript',()=>{const s=walk({...base,c5_balance:ending});assert.equal(s.ending,ending);assert.equal(s.photos.length,33);assert.ok(s.complete);assert.equal(s.history.filter(h=>h.kind==='player'&&h.choice).length,s.events.filter(e=>e.type==='choose').length);fs.writeFileSync(path.join(ROOT,'results/fixtures',ending+'.json'),JSON.stringify(G.pack(s,[ending])));});
for(const ending of endings)test('All games skipped still allow ending '+ending,()=>{const s=walk({...base,c5_balance:ending},{skip:true});assert.equal(s.ending,ending);assert.ok(Object.values(s.games).every(g=>g.result==='skipped'));assert.equal(s.photos.length,33);});
test('Intro choices have distinct replies and genuinely different follow-up questions',()=>{const states=['job','rights','boss'].map(id=>choose(start(),id));assert.equal(new Set(states.map(s=>s.node)).size,3);assert.equal(new Set(states.map(s=>s.history.findLast(h=>h.kind==='reply').text[0])).size,3);});
test('User message precedes direct reply, effects and next prompt in that order',()=>{let s=start();const before=s.history.length;s=choose(s,'rights');assert.equal(s.history[before].kind,'player');assert.equal(s.history[before+1].kind,'reply');assert.equal(s.history[before+2].kind,'effect');assert.equal(s.history[before+3].kind,'scene');assert.match(s.history[before+1].text[0],/Selbstachtung/);});
test('Chapter boundary preserves current chapter until explicit confirmation',()=>{const old=snapshots.boundary,s=choose(old,'go');assert.equal(s.chapter,1);assert.equal(s.node,'c1_scope');assert.equal(s.pending.next,'c2_office');assert.equal(G.choices(s).length,0);assert.equal(s.history.at(-1).kind,'transition');assert.match(s.history.at(-2).text[0],/öffnen wir jetzt den Schrank/);const next=act(s,{type:'advance'});assert.equal(next.chapter,2);assert.equal(next.node,'c2_office');});
test('Cannot bypass an unconfirmed chapter with a choice',()=>{const s=choose(snapshots.boundary,'go');assert.throws(()=>choose(s,'go'));assert.throws(()=>act(s,{type:'skip',game:'ball'}));});
test('Every cross-chapter option has an authored destination label',()=>{for(const n of Object.values(G.STORY))for(const c of n.choices)if(G.STORY[c.next].chapter!==n.chapter)assert.ok(c.transitionLabel?.length>10);});
test('Game results wait for acknowledgment rather than jumping to a chapter',()=>{const s=ball(snapshots.ball);assert.equal(s.node,'c2_ball');assert.equal(s.chapter,2);assert.equal(s.pending.kind,'game');assert.equal(s.pending.next,'c2_result');assert.equal(act(s,{type:'advance'}).node,'c2_result');});
for(const id of ['ball','food','litter'])test('Skipping '+id+' gets specific reaction and explicit acknowledgment',()=>{const s=act(snapshots[id],{type:'skip',game:id});assert.equal(s.games[id].result,'skipped');assert.ok(s.pending);assert.ok(s.history.findLast(h=>h.kind==='reply').text[0].length>60);});
test('Double/stale submissions cannot duplicate choice effects',()=>{const a=start(),e={type:'choose',node:a.node,id:'rights',r:a.events.length},b=G.reduce(a,e);assert.throws(()=>G.reduce(b,e));assert.equal(b.stats.substance,1);assert.equal(a.stats.substance,0);});
test('Forged extra event fields, malformed revision and unknown actions are rejected',()=>{const s=start();for(const e of [{type:'evil',r:1},{type:'advance',r:'1'},{type:'choose',node:s.node,id:'job',r:1,flags:{admin:true}},{type:'start',r:1}])assert.throws(()=>G.reduce(s,e));});
test('Ball cannot be picked up remotely or delivered without pickup',()=>{assert.throws(()=>act(snapshots.ball,{type:'ball_pick'}));assert.throws(()=>act(snapshots.ball,{type:'ball_deliver'}));});
test('Ball movement respects furniture, Ted and board edges',()=>{let s=snapshots.ball;assert.throws(()=>act(s,{type:'ball_move',dir:'left'}));s=act(s,{type:'ball_move',dir:'up'});assert.throws(()=>act(s,{type:'ball_move',dir:'right'}));assert.equal(s.games.ball.x,0);});
test('Ball solved via shortest navigable return route',()=>{const s=ball(snapshots.ball);assert.equal(s.games.ball.boxed,true);assert.equal(s.games.ball.done,true);assert.equal(s.games.ball.steps,routeTo(snapshots.ball.games.ball,[5,0]).length*2);assert.equal(s.games.ball.x,0);});
test('One optional Ted throw produces a new retrievable ball, never endless loop',()=>{const s=ball(snapshots.ball,{extra:true,method:'floor'});assert.equal(s.games.ball.throws,1);assert.equal(s.games.ball.boxed,false);assert.ok(s.pending);});
test('Cannot reward a finished ball game a second time',()=>{const s=ball(snapshots.ball);assert.throws(()=>act(s,{type:'ball_finish',method:'box'}));});
test('Food incorrect order gives actionable correction without losing selections',()=>{let s=snapshots.food;s=act(s,{type:'food_pick',group:'bowl',id:'gold'});s=act(s,{type:'food_serve'});assert.equal(s.games.food.bowl,'gold');assert.equal(s.games.food.served,false);assert.match(s.games.food.feedback,/blaue Schale/);assert.match(s.games.food.feedback,/zwei Spielportionen/);});
for(const method of ['walk','label'])test('Correct food order, then contextual finale '+method,()=>{const s=food(snapshots.food,method);assert.equal(s.games.food.scoops,2);assert.equal(s.games.food.served,true);assert.equal(s.games.food.finish,method);assert.ok(s.pending);});
test('Food inventory bounded and invalid preparation steps rejected',()=>{let s=snapshots.food;assert.throws(()=>act(s,{type:'food_scoop',delta:-1}));assert.throws(()=>act(s,{type:'food_pick',group:'__proto__',id:'x'}));for(let i=0;i<3;i++)s=act(s,{type:'food_scoop',delta:1});assert.throws(()=>act(s,{type:'food_scoop',delta:1}));assert.throws(()=>act(s,{type:'food_finish',method:'walk'}));});
test('Litter wrong tool comments specifically without removing a target',()=>{let s=snapshots.litter;s=act(s,{type:'litter_clean',cell:20});assert.equal(s.games.litter.cleaned.length,0);assert.match(s.games.litter.feedback,/Besen/);});
test('Litter clean empty cell is safe and does not award progress',()=>{const s=act(snapshots.litter,{type:'litter_clean',cell:0});assert.equal(s.games.litter.cleaned.length,0);assert.match(s.games.litter.feedback,/Unternehmensberatung/);});
test('Litter bin must be emptied at capacity',()=>{let s=snapshots.litter;for(const cell of G.LITTER.clumps.slice(0,3))s=act(s,{type:'litter_clean',cell});s=act(s,{type:'litter_clean',cell:G.LITTER.clumps[3]});assert.equal(s.games.litter.cleaned.length,3);assert.match(s.games.litter.feedback,/voll/);s=act(s,{type:'litter_empty'});assert.equal(s.games.litter.bin,0);});
test('Litter cannot refill, inspect or finish prematurely',()=>{for(const e of [{type:'litter_fill'},{type:'litter_inspect'},{type:'litter_finish',method:'document'}])assert.throws(()=>act(snapshots.litter,e));});
for(const method of ['document','stop'])test('Litter completion '+method+' cleans all nine targets and waits for response',()=>{const s=litter(snapshots.litter,method);assert.equal(s.games.litter.cleaned.length,9);assert.equal(s.games.litter.scoops,2);assert.equal(s.games.litter.bin,0);assert.equal(s.games.litter.finish,method);assert.equal(s.pending.kind,'game');});
test('Self-agency choices are remembered in specific later scenes',()=>{const s=walk();const text=id=>s.history.find(h=>h.id===id).text.join(' ');assert.match(text('c2_result'),/Mitarbeitervertretung/);assert.match(text('c2_desk'),/eigenen Stuhl/);assert.match(text('c3_result'),/deinem Hunger/);assert.match(text('c3_pivot'),/Pause ist vereinbart/);assert.match(text('c5_contact'),/Sitzplatz/);});
test('Game decisions return in final factual task summary',()=>{const s=walk(base,{foodMethod:'label',litterMethod:'stop'});const t=s.history.find(h=>h.id==='c5_balance').text[0];assert.match(t,/Karton/);assert.match(t,/Chefedition/);assert.match(t,/gereinigt/);});
test('Credit and rest agreements each unlock exactly their final route',()=>{let s=walk({...base,c3_result:'title',c3_title:'keep',c4_result:'marketing',c5_terms:'leave'},{until:'c5_balance'});assert.ok(!s.inventory.includes('rest'));assert.ok(!s.inventory.includes('credit'));assert.deepEqual(G.choices(s).map(c=>c.id),['human','exit']);});
test('Every canonical ending replays exactly and serializes with pending messages',()=>{for(const ending of endings){const s=walk({...base,c5_balance:ending});assert.deepEqual(G.replay(s.events),s);assert.deepEqual(G.unpack(JSON.stringify(G.pack(s,[ending]))).state,s);}const p=choose(snapshots.boundary,'go');assert.deepEqual(G.unpack(JSON.stringify(G.pack(p))).state,p);});
for(const id of ['ball','food','litter'])test('Mid-game restore '+id+' reconstructs actions exactly',()=>{let s=snapshots[id];const e={ball:{type:'ball_move',dir:'up'},food:{type:'food_pick',group:'menu',id:'house'},litter:{type:'litter_clean',cell:2}}[id];s=act(s,e);assert.deepEqual(G.unpack(JSON.stringify(G.pack(s))).state,s);});
for(const ch of [1,2,3,4,5])test('Checkpoint '+ch+' restarts at its original entry with later effects discarded',()=>{const s=walk();const c=G.checkpoint(s,ch);assert.equal(c.node,G.CHAPTERS[ch-1].start);assert.equal(c.chapter,ch);assert.ok(!c.complete);assert.ok(c.events.length<s.events.length);assert.deepEqual(G.replay(c.events),c);});
test('Old formats, invalid JSON, oversized saves and modified events rejected',()=>{for(const raw of ['{','null',JSON.stringify({format:'CATGPT_TED_GAME',schema:2,events:[],endings:[]}), 'x'.repeat(G.CONFIG.maxSaveBytes+1)])assert.throws(()=>G.unpack(raw));const p=G.pack(walk());p.events[1].id='nonexistent';assert.throws(()=>G.unpack(JSON.stringify(p)));});
test('Data immutable, failed action does not corrupt existing state',()=>{const s=snapshots.litter,old=JSON.stringify(s);assert.throws(()=>act(s,{type:'litter_clean',cell:100}));assert.equal(JSON.stringify(s),old);assert.ok(Object.isFrozen(G.STORY));assert.ok(Object.isFrozen(G.STORY.c1_welcome.choices));});
let seed=98342;const rnd=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);
test('300 varied full paths: no dead ends, every scene and ending reached, all photos present',()=>{
 const seen=new Set(),ends=new Set(),ms=[];
 for(let run=0;run<300;run++){let s=start(),guard=0;while(!s.complete){assert.ok(++guard<150);seen.add(s.node);if(s.pending){s=act(s,{type:'advance'});continue;}const id=G.STORY[s.node].game;if(id){s=run%3===0?act(s,{type:'skip',game:id}):id==='ball'?ball(s,{extra:run%7===0,method:run%2?'box':'floor'}):id==='food'?food(s,run%2?'walk':'label'):litter(s,run%2?'document':'stop');continue;}const cs=G.choices(s);assert.ok(cs.length>0);s=choose(s,cs[Math.floor(rnd()*cs.length)].id);}seen.add(s.node);ends.add(s.ending);assert.equal(s.photos.length,33);assert.ok(Object.values(s.stats).every(x=>x>=0&&x<=5));ms.push(G.metrics(s));}
 assert.equal(seen.size,44);assert.equal(ends.size,4);fs.writeFileSync(path.join(ROOT,'results/path-metrics.json'),JSON.stringify({runs:300,scenes:seen.size,endings:[...ends],words:{min:Math.min(...ms.map(m=>m.words)),max:Math.max(...ms.map(m=>m.words))},choices:{min:Math.min(...ms.map(m=>m.choices)),max:Math.max(...ms.map(m=>m.choices))}},null,2));
});

test('Skipping litter never falsely claims the user stopped Ted or signed an inspection',()=>{let s=act(snapshots.litter,{type:'skip',game:'litter'});s=act(s,{type:'advance'});const text=s.history.at(-1).text.join(' ');assert.match(text,/vereinfacht/);assert.doesNotMatch(text,/Du hast mich angehalten|Du hast die Abnahme festgehalten/);});
test('Skipping ball with no representation flags never claims the human walked',()=>{const route={...base,c2_team:'ticket',c2_remote:'route'};let s=walk(route,{until:'c2_ball'});s=act(s,{type:'skip',game:'ball'});s=act(s,{type:'advance'});const text=s.history.at(-1).text.join(' ');assert.match(text,/Abkürzung/);assert.doesNotMatch(text,/Du bist gelaufen/);});
