/* Photo-led edition. The shortened opening and new actions use save format 4. */
const rewrite=(id,text)=>{STORY[id].text=text;};
const caption=(id,title,note)=>{PHOTO_STORY[id].caption=title;if(note)PHOTO_STORY[id].note=note;};
CHAPTERS[0].title='Du hast den Job bereits.';CHAPTERS[0].task='Zur Firmenführung. Nicht versehentlich noch einen Arbeitsvertrag anklicken.';
CHAPTERS[2].short='Unbegrenztes Wachstum';CHAPTERS[2].title='Der Markt hat Hunger.';
CHAPTERS[3].short='Der erste echte Output';CHAPTERS[3].title='Das große Geschäft.';
CHAPTERS[4].short='Die große Vorführung';CHAPTERS[4].title='Ein Börsengang mit vier Pfoten.';
caption('judge','Bewerbung eingegangen. Du hast geklickt.','Die Personalabteilung hat dich überprüft: mindestens ein Finger, offenbar Internet. Überqualifiziert, aber verfügbar.');
caption('director','Vier Vorstände. Eine Katze. Null Haftung.','CEO, Personalchef, Ethikrat und Beschwerdestelle. Jede Pfote verweist auf eine andere Pfote.');
caption('alert','Jahresleistung: einmal aufrecht.','Bitte ein Foto machen. Für den Tätigkeitsbericht reicht es, wenn ich darauf senkrecht bin.');
caption('tilt','Ich suche den Winkel, aus dem das kostenlos klingt.','Deine Rückfrage hat meine Kopfhaltung verändert. Die erste Umstrukturierung ist damit abgeschlossen.');
caption('portfolio','Drei haben eine Glocke. Keiner einen Abschluss.','Die Bälle programmieren. Der Fisch betreut das Netz. Das Wollknäuel verwaltet die Verstrickungen. Ein Team mit erstaunlich wenig Gehaltsforderungen.');
caption('remoteit','Die IT hat sich räumlich gekündigt.','Der gelb-blaue Kollege sitzt hinter unserer Firewall. Das Tischgestell hat bisher jeden Angriff von mir abgewehrt. Ich habe allerdings noch keinen versucht.');
caption('mat','Geschäftsreise. Rückfahrt nicht budgetiert.','Vom Schrank auf die Matte. International wird es, sobald jemand die Balkontür aufmacht.');
caption('think','Zu hell für diese Unternehmenskultur.','Unsere hellste Mitarbeiterin. Ich habe ihr gekündigt. Sie hat mich schlecht aussehen lassen.');
caption('desk','Die Firewall ist jetzt körperlich.','Versuch mal, eine E-Mail durch meinen Arsch zu schicken. Sicherheit ist bei uns keine Software. Es ist eine Sitzordnung.');
caption('work','War maßgeblich in der Nähe beteiligt.','Der Laptop rechnet, der Mensch tippt. Ich liege im Bild. Die KI hat daraus eine Gründerbiografie gemacht.');
caption('security','Passwort: Lassmich. Zweiter Faktor: inruhe.','Zwei Augen. Zwei Faktoren. Sobald ich blinzle, gilt dein Zugang als widerrufen.');
caption('floor','Akuter Notfall. Napf nicht im Gesicht.','Ich bin bereits auf Bodenniveau. Wenn ich noch weiter entgegenkomme, müssen wir einen Keller bauen.');
caption('stretch','Wachstum, das die Matratze versteht.','Im letzten Quartal habe ich zwei Kissen übernommen. Die Kartellbehörde ist die Decke. Wir kennen uns privat.');
caption('solar','Nachhaltig. Bis zur nächsten Wolke.','Die Firma läuft mit Solarenergie. Sobald eine Wolke kommt, musst du mich mit einer Taschenlampe motivieren.');
caption('bed','Vor dem Essen bitte keine Bewegung.','Ich spare Energie für die Bewertung deines Essens. Ein anspruchsvoller Beruf mit sehr weichem Arbeitsweg.');
caption('duvet','Sterne-Küche. Das Muster hat Blumen.','Unsere Kantine ist botanisch zertifiziert. Ich habe das Blumenmuster eigenpfötig nicht ausgesucht.');
caption('wellness','Die Kissen tragen das Unternehmen.','Ich habe nach dem Mittagessen Verantwortung abgegeben. Hauptsächlich an dieses Polster.');
caption('upsidedown','Geschäftsführer gedreht. Zahlen gerettet.','Die Zahlen waren schlecht. Ich habe den Geschäftsführer gedreht. Jetzt geht alles nach oben.');
caption('sofa','Die Produktion läuft. Innerlich.','Der einzige Prozess, den ich heute selbst gestartet habe, endet leider in deinem Aufgabenbereich.');
caption('nap','Stand-by. Gehalt-by auch.','Ich schlafe nicht. Ich warte auf ein Update, das meine Arbeit erledigt. Bisher heißt das Update du.');
caption('lounge','Die Schaufel übernimmt den operativen Teil.','Ich habe mich extra hingesetzt, damit wir die Zuständigkeitslücke zwischen meinen Pfoten besprechen können.');
caption('chaos','Das Budget schaut zurück.','So sehe ich aus, wenn jemand meinen Output in Rechnung stellt. Ich dachte, Abfall wäre eine kostenlose Cloud.');
caption('approval','Geprüft mit geschlossenen Augen.','Ich prüfe mit geschlossenen Augen. So beeinflusst mich das Ergebnis nicht.');
caption('sun','Mitarbeiterbindung. Mechanisch.','Ich halte hier nur den Stoff fest. Falls dein Feierabend darin steckt, ist das ein bedauerlicher Zufall.');
caption('marketshare','Marktanteil: Sofa. Rest: ebenfalls Sofa.','Die linke Hälfte habe ich gekauft. Die rechte Hälfte habe ich besetzt. Der Kartellfall läuft beim Kissen.');
caption('edge','Kurz vor dem Durchbruch. Das Kissen zuerst.','Wir stehen an der Kapazitätsgrenze. Nicht an meiner. Ich habe meine nie ausprobiert.');
caption('boss','Führungsebene. Zwei Bretter höher.','Der Kratzbaum ist mein einziger nachweisbarer Karriereweg. Bitte im Lebenslauf trotzdem „organisches Wachstum“ schreiben.');
caption('closeup','Sachargument: dieses Gesicht.','Schau mir in die Augen und sag noch einmal, dass Anwesenheit keine Arbeitsleistung ist. Nein, nicht so überzeugend.');
caption('walkover','Die Übernahme ist abgeschlossen.','Bitte bewege das Unternehmen nicht. Ich liege darauf.');
caption('cozy','Ein warmer Moment. Ohne Anschlussauftrag.','Du bist anstrengend, aber warm. Das ist in meinem Bewertungssystem erstaunlich weit oben.');
caption('belly','Vollständige Offenlegung der Substanz.','Ein Bauch. Kein Produkt. Bitte beim Börsenprospekt die Reihenfolge tauschen.');
caption('paws','Die Pfoten stimmen für Feierabend.','Vier Ja-Stimmen. Die IT ist bereits unter den Tisch gerollt.');

Object.assign(STORY.c1_welcome.choices.find(c=>c.id==='job'),{label:'Gut. Zeig mir dein „Unternehmen“.',next:'c1_upright',reply:'Hervorragend. Du hast die Anführungszeichen bemerkt. Die Rechtsabteilung arbeitet daran.'});
STORY.c1_upright.photos=['director','alert'];STORY.c1_upright.photo='director';
rewrite('c1_welcome','Du hast geklickt. Die KI wertet das als Bewerbung. Willkommen bei CATGPT.\n\nHeute gehen wir an die Börse. Vorher musst du kurz die IT holen, das Management füttern und einen kleinen Produktionsrückstand beseitigen. Ich bin Ted. Mir gehört die Idee, dass du das machst.');
rewrite('c1_job','Dein Job: Head of Das-müsste-mal-jemand. Du führst eine Abteilung mit einem Mitarbeiter. Du.\n\nDer Vertrag liegt unter mir. Wir betrachten ihn deshalb als beidseitig belastet.');
delete STORY.c1_job;
rewrite('c1_pay','Vergütung: ein Blickkontakt pro Quartal. Obstkorb: Foto eines Apfels. Homeoffice: mein Home, dein Office.\n\nEin eigener Stuhl wäre verhandelbar, sobald ich mich für einen anderen entscheide.');
rewrite('c1_origin','Mein Gründungsprompt: „Mach mich reich, aber beschäftige mich nicht damit.“ Die KI hat eine Firma gebaut und dich reingelassen.\n\nDie erste Finanzierungsrunde war eine leere Schachtel. Ich habe hineingepasst. Alle waren begeistert.');
rewrite('c1_board',s=>['Vier Ämter. Eine Katze. Keine dieser Pfoten holt Bälle.',s.flags.titleFan?'Dein Titel ist inzwischen länger als unsere Gehaltsliste. Die Liste ist leer.':'Unsere Hierarchie ist flach. Direkt unter mir ist dein Stuhl.']);
rewrite('c1_board_question','Der Ethikrat sieht kein Problem. Seine Begründung: schnurr.\n\nWir haben übrigens eine unabhängige Kontrolle. Die Lampe sieht alles. Deshalb verdunkle ich sie gelegentlich.');
rewrite('c1_chair','Shared Desk heißt: Du teilst, ich liege. Dein eigener Stuhl steht vorerst nur als Konzept im Raum.\n\nIch schreibe ihn auf die Tagesordnung. Papier kann man wenigstens unter mich schieben.');
rewrite('c1_upright','So. Ich sitze aufrecht. Das war mein Beitrag zum heutigen Börsengang.\n\nDu übernimmst die drei Kleinigkeiten: Ball, Futter, Katzenklo. Die KI nennt es Operations. Ich nenne es einen sehr guten Tag für mich.');
rewrite('c1_scope',s=>[s.flags.threeOnly?'Drei Aufgaben. Die vierte habe ich in „freiwilliges Pflichtvergnügen“ umbenannt. Deinem Gesicht nach streichen wir die.':'Die Firmenführung beginnt. Bitte im Gebäude nicht an die Kleiderbügel stoßen.','Unser Hauptquartier hat zwei Regalböden. Die IT ist ein Ball. Er hat sich aus seiner Zuständigkeit gerollt.']);
rewrite('c2_office','Unser Hauptquartier. Die Wäsche dämmt den Schall. Das Scharnier ist die einzige Führungskraft, die etwas bewegt.\n\nDer gelb-blaue Ball ist die IT. Auf dem Foto ist er noch im Büro. Inzwischen macht er Homeoffice unter dem Tisch. Ohne Rücksprache. Sehr modern.');
rewrite('c2_team','Die Bälle entwickeln. Der Fisch betreut das Netz. Das Wollknäuel kümmert sich um Verstrickungen.\n\nAlle arbeiten agil: Sobald man sie braucht, sind sie woanders. Wir suchen den gelb-blauen Kollegen. Bitte nicht die Buchhaltung apportieren.');
rewrite('c2_remote','Der Kollege sitzt hinter der Firewall. Ein Tischgestell.\n\nTippe im Zimmerplan auf ein freies Ziel. Dein Mensch läuft hin. Bring den Ball zurück. Ich bin auch im Weg. Das ist mein Führungsstil.');
rewrite('c2_ball','Tippe auf den Ball, heb ihn auf und bring ihn zum Start zurück. Möbel und Geschäftsleitung bleiben liegen.');
rewrite('c2_outpost','Das ist unsere Außenstelle. Ich bin vom Schrank zur Matte gereist und zur Vermeidung weiterer Kosten geblieben.\n\nIm Prospekt steht „international aufgestellt“. Die Balkontür war offen.');
rewrite('c2_lamp','Die Lampe arbeitet seit Stunden. Ohne Meeting. Ohne Titel. Ohne LinkedIn-Post über ihren Weg von der Steckdose zum Erfolg.\n\nSehr illoyal. Befördern wir sie oder drehen wir ihre Leistung runter?');
rewrite('c2_desk',s=>['Die KI macht den Code. Du machst die Eingaben. Ich blockiere den Arbeitsplatz. Drei Spezialisten.',s.flags.ownChair?'Deinen eigenen Stuhl gebe ich frei. Der Schreibtisch gehört weiter der physischen Firewall.':'Wir haben zwei Bildschirme und null Tastaturzugang. Sicherheit durch Körpermasse.','Auf dem Laptop liegt das Gründungsprotokoll. Das Gesicht hier wirkt allerdings deutlich professioneller.']);
rewrite('c2_space','Ich bin eine Pfotenbreite gerutscht. Die Pressemitteilung spricht von einem Standortwechsel.\n\nDu kommst jetzt ans Protokoll. Schnell, bevor die Geschäftsleitung rückexpandiert.');
rewrite('c2_protocol','Website: KI. Code: KI. Personalbeschaffung: KI. Mein Beitrag: „Mach es erfolgreich, aber beschäftige mich nicht.“\n\nBitte speichern. Unter „Vision“, nicht unter „Beweismittel“.');
rewrite('c2_security',s=>[has(s,'protocol')?'Du hast das Protokoll. Der Datenschutzbeauftragte ist beleidigt. Ich bin das übrigens auch.':'Zugangskontrolle bestanden. Du siehst nützlich aus.','Die IT ist zurück. Jetzt fällt unser größter Kunde aus: mein Magen. Er hat seit der letzten Mahlzeit nichts bekommen.']);
rewrite('c3_hunger',s=>['Akuter Engpass. Ich liege schon auf Napfhöhe. Noch näher dran wäre ich Teil der Bestellung.',s.flags.humanHungry?'Deinen Hunger führen wir ab jetzt als zweiten Standort.':'Die Nachfrage ist riesig. Der Markt bin ich.','Das Budget bist du. Eine erfreulich einfache Finanzstruktur.']);
rewrite('c3_growth','Leider kann auch erneuerbare Energie keine Dose öffnen. Der Sonne fehlt der Daumen.\n\nDeshalb haben wir dich eingestellt. Die KI fand fünf Finger übertrieben, aber du warst gerade da.');
rewrite('c3_order','Das Blumenmuster ist unsere Kantinengestaltung. Sehr exklusiv. Ich habe es nicht bezahlt.\n\nMeine Bestellung: Hausmenü, blaue Schale, zwei Portionen und Wasser. Danach darfst du entscheiden, ob ich hinlaufe oder das Essen einen teureren Namen bekommt.');
rewrite('c3_food','Stelle die Bestellung zusammen. Danach retten wir den Markenwert mit einem Etikett.');
rewrite('c3_result',s=>[s.games.food.result==='skipped'?'Vorbereitete Portion akzeptiert. Mein Magen hat den fehlenden Projektplan nicht bemerkt.':s.games.food.finish==='label'?`„${s.games.food.brand||'Chefedition'}“. Dasselbe Futter, neues Etikett. Ich finde es plötzlich hervorragend. Bitte nie auf mich als Investor vertrauen.`:'Ich bin selbst zum Napf gegangen. Die Geschäftsleitung verlangt vier Tage Regeneration.',s.flags.humanHungry?'Jetzt zu deinem Hunger. Du bekommst eine Pause statt einer Ticketnummer.':'Die Kissen tragen jetzt den gesamten Vorstand. Eine Karriere ohne Aufstieg.','Was darf’s für dich sein? Eine Pause, ein Anteil oder ein völlig nutzloser Titel?']);
rewrite('c3_agreement','Pause für beide. Schriftlich. Die Rechtsabteilung hat versucht, „beide“ durch „Ted“ zu ersetzen. Du warst schneller.\n\nNoch ein Wunsch, bevor ich die Pfote vom Dokument nehme?');
rewrite('c3_credit','Dein Name unter deiner Arbeit. Meiner auf dem Gebäude. So erkennt man schon von außen, wer nichts tragen musste.\n\nDas ist ab jetzt schriftlich. Mit einer überraschend widerwilligen Pfote bestätigt.');
rewrite('c3_title','Chief Napkin Officer. Du wischst alles auf. Ich lasse dich in einer Präsentation kreisförmig darstellen.\n\nOder du nimmst die Pause. Aber die hat keine Visitenkarte.');
rewrite('c3_pivot',s=>['Geschäftsführer gedreht. Problem gelöst. Die Folien stehen jetzt kopfüber, also geht der Verlust nach oben.',has(s,'rest')?'Deine Pause ist vereinbart. Noch genau eine Aufgabe.':'Noch eine Aufgabe, dann die Vorführung.','Das Katzenklo. Ich habe den produktiven Teil bereits persönlich übernommen.']);
rewrite('c4_mission','Die Produktion läuft. Mein Darm ist gerade die einzige Abteilung mit messbarem Output.\n\nDu übernimmst die Altlasten. Ich habe ein Tool beschafft. Es ist eine Schaufel. Sie braucht kein Passwort.');
rewrite('c4_tools',s=>[s.flags.teamRespect?'Die Mitarbeitervertretung der Bälle lehnt den Schaufeldienst ab. Begründung: rund. Juristisch erstaunlich wasserdicht.':'Die Schaufel ist unser einziges Tool ohne Abo. Ich wollte 9,99 im Monat verlangen. Sie hat nicht reagiert.','Klumpen weg, Spuren weg, Streu rein. Danach prüfe ich das Ergebnis mit geschlossenen Augen. So bleibe ich unvoreingenommen.']);
rewrite('c4_litter','Schaufel für Klumpen, Besen für Spuren. Du sanierst. Ted nimmt später den Preis entgegen.');
rewrite('c4_debrief',s=>['Ball zurück. Napf voll. Anlage sauber. Ich habe in derselben Zeit drei Unterlagen getestet: Sofa, Bett, dich.',s.flags.ownChair?'Dein eigener Sitzplatz wird gerade freigegeben. Vom Konzept her.':s.flags.workSpace?'Du hast den Schreibtisch erobert. Ich plane bereits eine Wiederbesetzung.':'Die ganze Sofafläche gehört zum Konzern. Du darfst als Randnotiz sitzen.','Du bist fertig. Das ist ein schwerer Fehler im Geschäftsmodell.']);
rewrite('c4_thanks','Danke. Ehrlich. Du hast geholfen, obwohl diese Firma zu 90 Prozent aus meiner Liegeposition besteht.\n\nBitte keinen Screenshot. Die Investoren halten mich für emotional nicht zuständig.');
rewrite('c4_edge',s=>['Kurz vor dem Durchbruch. Das Kissen hat schon nachgegeben.',has(s,'credit')?'Deine Zusage gilt. In der Bilanz muss ich erstmals unter meinem eigenen Beitrag unterschreiben. Die Zeile ist erschreckend kurz.':has(s,'rest')?'Deine Pause gilt. Der Vorstand sucht vergeblich nach einem Sternchen.':'Du bist fertig. Der nächste Ball ist keine automatische Vertragsverlängerung.','Zur Vorführung. Ich gehe schon einmal zwei Bretter höher. Kompetenz braucht Abstand.']);
rewrite('c5_reveal',s=>[s.flags.sawTwist?'Du hast es geahnt: Die Vorführung läuft seit deinem ersten Klick.':'Überraschung: Die Vorführung warst du. Die KI hat eine Seite gebaut, die einen Menschen dazu bringt, meinen Katzentag zu erledigen.','Unser Produkt heißt Mensch-as-a-Service. Der Server bist du. Das Abo habe ich vergessen zu erwähnen.','Der Börsengang findet auf dem Kratzbaum statt. Die Bälle sind Investoren. Die Mehrheit ist unter den Tisch gerollt.']);
rewrite('c5_contact',s=>['Die Übernahme ist abgeschlossen. Bitte bewege das Unternehmen nicht. Ich liege darauf.',s.flags.ownChair?'Dein Sitzplatz ist frei. Ich wollte nur prüfen, ob du warm genug dafür bist.':s.flags.thanksNoted?'Du hast mein Danke notiert. Ich bestreite nur die Herzchen in der Formatierung.':'Ja, ich mag dich. Du bist warm und kannst Dosen öffnen. Es wäre absurd, da keine Gefühle zu entwickeln.','Das ist kein neuer Auftrag. Einmal kraulen ist optional. Laut Personalabteilung. Also mir, vor fünf Minuten.']);
// Keep the factual result functions: they distinguish actual actions from shortcuts.
STORY.c2_lamp.choices[0].label='Befördere sie zur Stehlampe.';
STORY.c2_lamp.choices[0].reply='Chief Illumination Officer. Die Lampe bekommt die Anerkennung. Sie hat abgelehnt, meinen Namen mit auszuleuchten. Sehr unabhängige Führungskraft.';
STORY.c2_lamp.choices[1].label='Die Lampe führt ab jetzt dich.';
STORY.c2_lamp.choices[1].reply='Sie steht bereits über mir. Wir nennen das flache Hierarchie und stellen sie vorsichtshalber auf den Boden.';
STORY.c3_growth.choices[0].label='Ich kündige. Frag die Sonne.';
STORY.c3_growth.choices[0].reply='Die Sonne hat um 18 Uhr einen anderen Kunden. Du bleibst vorerst mein Daumen mit Internetanschluss.';
STORY.c4_mission.choices[2].label='Endlich ein Produkt. Leider scheiße.';
STORY.c4_mission.choices[2].reply='Organisch gewachsen. Regional produziert. Die Marketingabteilung hat sich seit heute Morgen nicht mehr eingekriegt.';
STORY.c5_balance.choices[0].label='Wir gründen neu. Die Lampe prüft die Bilanz.';
STORY.c5_balance.choices[1].label='Ich spiele mit. Befördere mich ins Lächerliche.';
STORY.c5_balance.choices[2].label='Firma zu. Beide auf die Couch.';
STORY.c5_balance.choices[3].label='Ich gehe. Der Ball wird dein Nachfolger.';
ENDINGS.founder.last='Dein Name steht unter der Arbeit. Die Lampe prüft die Bilanz. Ich habe versucht, sie zu bestechen. Sie nimmt nur Strom. Ein sehr schwieriger Markt.';
ENDINGS.human.last='Hiermit ernenne ich dich zum Senior Executive Chief of Alles. Du bekommst einen Untergebenen: dich von morgen. Bitte arbeite ihn heute noch ein. Nein? Schade.';
ENDINGS.rest.last='Die Firma ist geschlossen. Du liegst. Ich liege. Zum ersten Mal stimmt unser Geschäftsmodell mit den tatsächlichen Tätigkeiten überein.';
ENDINGS.exit.last='Der Ball übernimmt deine Stelle. Er ist rund, schweigt und lässt sich herumschubsen. Ein ideales Profil. Leider kann er keine Dose öffnen. Ich glaube, ich habe einen Fehler gemacht.';
for(const ending of Object.keys(ENDINGS)){
 const previous=STORY['c5_end_'+ending].text;
 STORY['c5_end_'+ending].text=s=>{const text=previous(s);text[0]=ENDINGS[ending].last;return text;};
}
